In [2]:
import numpy as np

def create_co_matrix(corpus, vocab_size, window_size=1):
    corpus_size = len(corpus)
    co_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)
    
    for idx, word_id in enumerate(corpus):
        for i in range(1, window_size+1):
            left_idx = idx-i
            right_idx = idx+i
            
            if left_idx >= 0:
                left_word_id = corpus[left_idx]
                co_matrix[word_id, left_word_id] += 1
            
            if right_idx < corpus_size:
                right_word_id = corpus[right_idx]
                co_matrix[word_id, right_word_id] += 1
                
    return co_matrix

## Gradient Descent

In [1]:
# tensorflow

import tensorflow as tf
optimizer = tf.optimizers.SGD(0.01, momentum=0.01)

In [2]:
# pytorch

import torch
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.01)

NameError: name 'model' is not defined

## NLP

### RNN

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
sentences = ['i like dog', 'i love coffee', 'i hate milk', 'you like cat', 'you love milk', 'you hate coffee']
dtype = torch.float

word_list = list(set(' '.join(sentences).split()))
word_dict = {w: i for i, w in enumerate(word_list)}
number_dict = {i: w for i, w in enumerate(word_list)}
n_class = len(word_dict)

In [4]:
n_class

9

In [16]:
sentences[0].split()[:-1]

['i', 'like']

In [9]:
# RNN parameters

batch_size = len(sentences)
n_step = 2 # 학습하고자 하는 문장의 길이 - 1
n_hidden = 5 

def make_batch(sentences):
    input_batch = []
    target_batch = []
    
    for sen in sentences:
        word = sen.split()
        input = [word_dict[n] for n in word[:-1]] # 문장 중 마지막 단어 제외하고 모두 input
        target = word_dict[word[-1]]
        
        input_batch.append(np.eye(n_class)[input]) # one-hot encoding
        target_batch.append(target)
        
    return input_batch, target_batch

In [17]:
np.eye(n_class)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
input_batch, target_batch = make_batch(sentences)
input_batch

[array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.]]),
 array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.]]),
 array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.]]),
 array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.]])]